name: Saludo usando variables
run-name: ¡Estoy aprendiendo a usar Variables!
on: workflow_dispatch
# sepueden configurar variables de entorno desde cualquier lugar del flujo de trabajo
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Danniel
